# syntax=docker/dockerfile:1
FROM ruby:3.3.3
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
WORKDIR /sample_app3
COPY Gemfile /sample_app3/Gemfile
COPY Gemfile.lock /sample_app3/Gemfile.lock
RUN bundle install

# Add a script to be executed every time the container starts.
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
# 環境変数PORTを設定
ENV PORT=3000
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

# Configure the main process to run when running the image
CMD ["rails", "server", "-b", "0.0.0.0", "-p", "3000"]